name: VIM CI

on:
  push:
    branches: [master, develop, staging]
  pull_request:
    branches: [master, develop, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # run 'yarn install'
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # run 'yarn build'
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: yarn ci # run 'yarn ci'
