name: VIM CI

on:
  push:
    branches: [master, develop, staging]
  pull_request:
    branches: [master, develop, staging]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # run 'yarn install'
      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # run 'yarn build'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check code with eslint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: eslint:check # run 'yarn eslint:check'
