name: VIM Staging CI/CD

on:
  push:
    branches: [staging]

  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: check code with eslint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: eslint:check

  deploy:
    needs: [build, test]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: set ENV && yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: ENV REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} && ENV REACT_APP_VIM_URL_STAGING=${{ secrets.REACT_APP_VIM_URL_STAGING }} && build

      - name: deploy to surge
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: add global surge
          cmd: cd build && move index.html 200.html && surge ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}